server:
  port: 8080
spring:
  main:
    banner-mode: off
  rabbitmq:
    port: 5678
    username: guest
    password: guest
  queue:
    name: queueDima
  data:
    mongodb:
      username: test
      password: 123
      uri: mongodb://192.168.1.205:27018
      database: db
    liquibase:
      change-log: classpath:resources/migration.xml